/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ElementQuery {
  automationId?: string
  name?: string
  controlType?: string
  className?: string
  nameMatch?: string
  maxDepth?: number
  maxNodes?: number
  index?: number
  includeOffscreen?: boolean
}

export declare function findElement(hwnd: number, query: ElementQuery, options?: UiaOptions | undefined | null): UiaNode | null

export declare function getElementValue(hwnd: number, query: ElementQuery): string

export declare function getUiTree(hwnd: number, options?: UiaOptions | undefined | null): UiaNode

export declare function invokeElement(hwnd: number, query: ElementQuery): void

export declare function ping(): string

export declare function setElementValue(hwnd: number, query: ElementQuery, value: string): void

export interface UiaNode {
  name: string
  controlType: string
  automationId: string
  className: string
  boundingRect: UiaRect
  isEnabled: boolean
  isOffscreen: boolean
  value?: string
  children: Array<UiaNode>
}

export interface UiaOptions {
  timeoutMs?: number
  maxDepth?: number
  maxNodes?: number
  includeOffscreen?: boolean
}

export interface UiaRect {
  x: number
  y: number
  w: number
  h: number
}
